/*
 * AStarForwardShortestPath.h
 *
 *  Created on: 22 Aug 2015
 *  Author: Gabor Makrai
 */

#ifndef ASTARFORWARDSHORTESTPATH_H_
#define ASTARFORWARDSHORTESTPATH_H_

#include "../ShortestPath.h"

/**
 *
 * Class stores the calculated shortest path generated by the AStarForwardBinaryHeap class
 *
 */
class AStarForwardShortestPath : public ShortestPath {
public:
	int* storage;
	int current;
	AStarForwardShortestPath(int* storage);
	bool hasNext();
	int next();
	void addRoad(int id);
};


#endif /* ASTARFORWARDSHORTESTPATH_H_ */
